version: '3'
services:
  jenkins:
    container_name: jenkins
    build:
        context: .
        dockerfile: Dockerfile
    image: jenkins-casc
    ports:
      - "8080:8080" 
    volumes:
      - ./jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CASC_JENKINS_CONFIG: /var/jenkins_home/casc_configs/jenkins.yaml

volumes:
  jenkins_home:
